import { NextResponse } from 'next/server';
import OpenAI from 'openai';

const openai = new OpenAI({
    apiKey: process.env.TOGETHER_API_KEY,
    baseURL: "https://api.together.xyz/v1",
});

export async function POST(request: Request) {
    try {
        const { query, location } = await request.json();

        const city = location?.city || 'Unknown City';
        const country = location?.country || 'Unknown Country';

        if (!process.env.TOGETHER_API_KEY) {
            return NextResponse.json(
                { error: 'Together API Key not configured' },
                { status: 500 }
            );
        }

        const prompt = `
      You are a local guide assistant.
      User Location: ${city}, ${country}
      User Query: "${query}"

      Task:
      1. Find 3 real or realistic recommendations for the query in this location.
      2. Provide a title, description (1 sentence), address (street name is enough), and a rating (4.0-5.0).
      3. Write a short summary paragraph (2-3 sentences) explaining the top choice.

      Return ONLY valid JSON in this format:
      {
        "results": [
          { "title": "...", "description": "...", "address": "...", "rating": 4.5 }
        ],
        "summary": "..."
      }
    `;

        const completion = await openai.chat.completions.create({
            messages: [{ role: "user", content: prompt }],
            model: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
            response_format: { type: "json_object" },
        });

        const content = completion.choices[0].message.content;
        if (!content) {
            throw new Error('No content received from AI');
        }

        const data = JSON.parse(content);

        return NextResponse.json({
            results: data.results,
            summary: data.summary,
            ai_context: `Generated by Together.ai (Llama 3.1) for "${query}" in ${city}`
        });

    } catch (error) {
        console.error('AI Search Error:', error);
        return NextResponse.json(
            { error: 'Failed to generate recommendations' },
            { status: 500 }
        );
    }
}
